# 2021 年 12 月 20 日工作总结

昨日下午有同学反馈自己的 Vivado 项目在 Vlab 上生成比特流时总是失败。昨日晚与今日凌晨对该问题进行了排查。

首先发现该问题确实存在，Vivado 输出的崩溃时错误栈开头一部分如下：

```
Stack:
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f3cc17f8210]
/lib/x86_64-linux-gnu/libc.so.6(malloc_usable_size+0x48) [0x7f3cc1851378]
/lib/x86_64-linux-gnu/libudev.so.1(+0x10319) [0x7f3c77539319]
/lib/x86_64-linux-gnu/libudev.so.1(+0x167c4) [0x7f3c7753f7c4]
/lib/x86_64-linux-gnu/libudev.so.1(+0x1b255) [0x7f3c77544255]
/lib/x86_64-linux-gnu/libudev.so.1(+0x1b4bb) [0x7f3c775444bb]
/lib/x86_64-linux-gnu/libudev.so.1(udev_enumerate_scan_devices+0x277) [0x7f3c77546d67]
```

尝试使用 Ubuntu 18.04 Docker 运行 Vivado，生成正常。在检索相关资料后，我们认为该问题可能是 Ubuntu 20.04 的 libudev.so 与 Vivado 2019.1 不兼容导致的，或为 libudev 在 LXC 容器中触发了某些 corner case。将 Ubuntu 18.04 的 libudev.so 提取后，加入 `LD_PRELOAD` 中，再次运行 Vivado，生成正常。

相关修改已经部署到 Vlab Software 中。
